#services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=runnerz'
#      - 'POSTGRES_PASSWORD=password'
#      - 'POSTGRES_USER=chinh'
#    ports:
#      - '5432:5432'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=runnerz'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=chinh'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql